version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  stationski:
    image: ikramdhibikram/stationski:1.0
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "8089:8089"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
